### ISSUE TITLE
Virtualizor default username/password

### ISSUE THREAD

**Issue by GeorgeV220** [Ivstiv/virtualizor-docker#4]
Hello,
I have set the password in docker compose yml but I can't login in the admin panel.. which is the correct username ??

**Comment by ivstiv** [comment]
I believe the username is 'root', will double check later if there are any login issues on a fresh install.

**Comment by GeorgeV220** [comment]
thank you for your reply, I tried with root but I can't login with the password that I have set at the docker compose file. I will reinstall it to check if I did something wrong

**Comment by ivstiv** [comment]
Pop into my discord if you continue to struggle, so we can go through your setup and check the logs to make sure that the installation has gone through fine.
https://discord.gg/VMSDGVD
